name: Tech Talk
description: Tech Talk for JUG
title: "[Tech Talk]: "
labels: ["enhancement"]
assignees:
  - sathishk
body:
  - type: markdown
    attributes:
      label: Abstract of the Talk
      description: Abstract of the Talk
    validations:
      required: true
  - type: markdown
    attributes:
      label: Speaker(s) Bio
      description: Speaker(s) Details
    validations:
      required: true      