name: Tech Talk
description: Submiting a Tech talk for JUG Meetup.
title: "[TECH TALK]: "
body:
  - type: markdown
    attributes:
      label: Abstract
  - type: markdown
    attributes:
      label: Speaker Bio
      description: Speaker Bio of the Talk
  - type: dropdown
    id: version
    attributes:
      label: Categoty
      description: What categoty suits your talk?
      options:
        - Core Java
        - JVM Internals
        - Spring Boot
      default: 0
    validations:
      required: true
